#!/bin/echo Use as an argument to mkroot.sh

set -ex

download a5d40ca0201b20909f7a8a561adf57adccc8a877 \
  https://busybox.net/downloads/busybox-1.36.1.tar.bz2

setupfor busybox
cp ../../../..//busybox.config .config &&

make &&
LDFLAGS=--static make install CONFIG_PREFIX="$ROOT" SKIP_STRIP=y -j $(nproc)
