/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: package.proto */

#ifndef PROTOBUF_C_package_2eproto__INCLUDED
#define PROTOBUF_C_package_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1004001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct PackageMetaContent PackageMetaContent;
typedef struct PackageFileMeta PackageFileMeta;


/* --- enums --- */


/* --- messages --- */

struct  PackageMetaContent
{
  ProtobufCMessage base;
  ProtobufCBinaryData name;
  ProtobufCBinaryData description;
  uint32_t majorversion;
  uint32_t minorversion;
  uint32_t revision;
};
#define PACKAGE_META_CONTENT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&package_meta_content__descriptor) \
    , {0,NULL}, {0,NULL}, 0, 0, 0 }


struct  PackageFileMeta
{
  ProtobufCMessage base;
  uint32_t stat;
  uint32_t uid;
  uint32_t gid;
  uint64_t atimsec;
  uint64_t atimnsec;
  uint64_t mtimsec;
  uint64_t mtimnsec;
  uint64_t ctimsec;
  uint64_t ctimnsec;
  char *md5;
  char *name;
};
#define PACKAGE_FILE_META__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&package_file_meta__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0, 0, 0, (char *)protobuf_c_empty_string, (char *)protobuf_c_empty_string }


/* PackageMetaContent methods */
void   package_meta_content__init
                     (PackageMetaContent         *message);
size_t package_meta_content__get_packed_size
                     (const PackageMetaContent   *message);
size_t package_meta_content__pack
                     (const PackageMetaContent   *message,
                      uint8_t             *out);
size_t package_meta_content__pack_to_buffer
                     (const PackageMetaContent   *message,
                      ProtobufCBuffer     *buffer);
PackageMetaContent *
       package_meta_content__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   package_meta_content__free_unpacked
                     (PackageMetaContent *message,
                      ProtobufCAllocator *allocator);
/* PackageFileMeta methods */
void   package_file_meta__init
                     (PackageFileMeta         *message);
size_t package_file_meta__get_packed_size
                     (const PackageFileMeta   *message);
size_t package_file_meta__pack
                     (const PackageFileMeta   *message,
                      uint8_t             *out);
size_t package_file_meta__pack_to_buffer
                     (const PackageFileMeta   *message,
                      ProtobufCBuffer     *buffer);
PackageFileMeta *
       package_file_meta__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   package_file_meta__free_unpacked
                     (PackageFileMeta *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*PackageMetaContent_Closure)
                 (const PackageMetaContent *message,
                  void *closure_data);
typedef void (*PackageFileMeta_Closure)
                 (const PackageFileMeta *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor package_meta_content__descriptor;
extern const ProtobufCMessageDescriptor package_file_meta__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_package_2eproto__INCLUDED */
