/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: package.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "package.pb-c.h"
void   package_meta_content__init
                     (PackageMetaContent         *message)
{
  static const PackageMetaContent init_value = PACKAGE_META_CONTENT__INIT;
  *message = init_value;
}
size_t package_meta_content__get_packed_size
                     (const PackageMetaContent *message)
{
  assert(message->base.descriptor == &package_meta_content__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t package_meta_content__pack
                     (const PackageMetaContent *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &package_meta_content__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t package_meta_content__pack_to_buffer
                     (const PackageMetaContent *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &package_meta_content__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PackageMetaContent *
       package_meta_content__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PackageMetaContent *)
     protobuf_c_message_unpack (&package_meta_content__descriptor,
                                allocator, len, data);
}
void   package_meta_content__free_unpacked
                     (PackageMetaContent *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &package_meta_content__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   package_file_meta__init
                     (PackageFileMeta         *message)
{
  static const PackageFileMeta init_value = PACKAGE_FILE_META__INIT;
  *message = init_value;
}
size_t package_file_meta__get_packed_size
                     (const PackageFileMeta *message)
{
  assert(message->base.descriptor == &package_file_meta__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t package_file_meta__pack
                     (const PackageFileMeta *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &package_file_meta__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t package_file_meta__pack_to_buffer
                     (const PackageFileMeta *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &package_file_meta__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
PackageFileMeta *
       package_file_meta__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (PackageFileMeta *)
     protobuf_c_message_unpack (&package_file_meta__descriptor,
                                allocator, len, data);
}
void   package_file_meta__free_unpacked
                     (PackageFileMeta *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &package_file_meta__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor package_meta_content__field_descriptors[5] =
{
  {
    "name",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PackageMetaContent, name),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "description",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(PackageMetaContent, description),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "majorVersion",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PackageMetaContent, majorversion),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "minorVersion",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PackageMetaContent, minorversion),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "revision",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PackageMetaContent, revision),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned package_meta_content__field_indices_by_name[] = {
  1,   /* field[1] = description */
  2,   /* field[2] = majorVersion */
  3,   /* field[3] = minorVersion */
  0,   /* field[0] = name */
  4,   /* field[4] = revision */
};
static const ProtobufCIntRange package_meta_content__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor package_meta_content__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PackageMetaContent",
  "PackageMetaContent",
  "PackageMetaContent",
  "",
  sizeof(PackageMetaContent),
  5,
  package_meta_content__field_descriptors,
  package_meta_content__field_indices_by_name,
  1,  package_meta_content__number_ranges,
  (ProtobufCMessageInit) package_meta_content__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor package_file_meta__field_descriptors[11] =
{
  {
    "stat",
    1,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PackageFileMeta, stat),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "uid",
    2,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PackageFileMeta, uid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "gid",
    3,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT32,
    0,   /* quantifier_offset */
    offsetof(PackageFileMeta, gid),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "AtimSec",
    4,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PackageFileMeta, atimsec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "AtimNsec",
    5,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PackageFileMeta, atimnsec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "MtimSec",
    6,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PackageFileMeta, mtimsec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "MtimNsec",
    7,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PackageFileMeta, mtimnsec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "CtimSec",
    8,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PackageFileMeta, ctimsec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "CtimNsec",
    9,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_UINT64,
    0,   /* quantifier_offset */
    offsetof(PackageFileMeta, ctimnsec),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "md5",
    10,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PackageFileMeta, md5),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "name",
    11,
    PROTOBUF_C_LABEL_NONE,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(PackageFileMeta, name),
    NULL,
    &protobuf_c_empty_string,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned package_file_meta__field_indices_by_name[] = {
  4,   /* field[4] = AtimNsec */
  3,   /* field[3] = AtimSec */
  8,   /* field[8] = CtimNsec */
  7,   /* field[7] = CtimSec */
  6,   /* field[6] = MtimNsec */
  5,   /* field[5] = MtimSec */
  2,   /* field[2] = gid */
  9,   /* field[9] = md5 */
  10,   /* field[10] = name */
  0,   /* field[0] = stat */
  1,   /* field[1] = uid */
};
static const ProtobufCIntRange package_file_meta__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 11 }
};
const ProtobufCMessageDescriptor package_file_meta__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "PackageFileMeta",
  "PackageFileMeta",
  "PackageFileMeta",
  "",
  sizeof(PackageFileMeta),
  11,
  package_file_meta__field_descriptors,
  package_file_meta__field_indices_by_name,
  1,  package_file_meta__number_ranges,
  (ProtobufCMessageInit) package_file_meta__init,
  NULL,NULL,NULL    /* reserved[123] */
};
